"""Fix Train foreign key to MetroLine

Revision ID: 4a5af68d1d8d
Revises: e9b269199553
Create Date: 2025-09-10 17:04:17.228039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5af68d1d8d'
down_revision = 'e9b269199553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('train', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
        'fk_train_line_id',     # ✅ Named constraint
        'metro_line',
        ['line_id'],
        ['id']
    )
                # Remote column
        batch_op.drop_column('route_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('train', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('line_id')

    # ### end Alembic commands ###
