"""Add reply and reply_method to Complaint

Revision ID: 4bc57a908a08
Revises: 5f4c465eb903
Create Date: 2025-09-13 07:37:57.032204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bc57a908a08'
down_revision = '5f4c465eb903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('reply', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reply_method', sa.String(length=10), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=200),
               nullable=True)
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('station', schema=None) as batch_op:
        batch_op.drop_column('zone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zone', sa.VARCHAR(length=10), nullable=False))

    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('subject',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('reply_method')
        batch_op.drop_column('reply')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
