"""Add status column to User

Revision ID: 787171bef392
Revises: 8e6b911513f1
Create Date: 2025-09-12 20:50:14.145766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787171bef392'
down_revision = '8e6b911513f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
