"""Add zone to Station

Revision ID: 88aec8443210
Revises: 40b8b65baa76
Create Date: 2025-09-12 15:46:07.582985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88aec8443210'
down_revision = '40b8b65baa76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zone', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station', schema=None) as batch_op:
        batch_op.drop_column('zone')

    # ### end Alembic commands ###
