"""Add Train model

Revision ID: a9cbca0f3ec0
Revises: 4a5af68d1d8d
Create Date: 2025-09-10 17:09:55.578389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9cbca0f3ec0'
down_revision = '4a5af68d1d8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    def upgrade():
        op.create_table(
            'train',
            sa.Column('id', sa.Integer(), primary_key=True),
            sa.Column('name', sa.String(length=100), nullable=False, unique=True),
            sa.Column('line_id', sa.Integer(), sa.ForeignKey('metro_line.id'), nullable=False)
        )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('train')